radio.onReceivedString(function (receivedString) {
    basic.showString(receivedString)
    basic.clearScreen()
    radio.setGroup(3)
    basic.pause(2000)
    radio.sendString("test")
    radio.setGroup(2)
})
basic.showIcon(IconNames.SmallHeart)
basic.clearScreen()
radio.setGroup(2)
radio.setTransmitPower(0)
basic.forever(function () {
    radio.sendString("1")
})
